<a href="https://colab.research.google.com/github/eunjaelim/pytorch/blob/master/2_3_tensor_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

In [6]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

In [7]:
print(m1+m2)

tensor([[5., 5.]])


In [9]:
m3 = torch.FloatTensor([1,2])
m4 = torch.FloatTensor([3])

In [11]:
print([[4,5]])

[[4, 5]]


In [14]:
m5 = torch.FloatTensor([[1,2]])
m6 = torch.FloatTensor(([3],[4]))

In [20]:
# 덧셈
m5+m6

tensor([[4., 5.],
        [5., 6.]])

In [21]:
print(m5.shape,m6.shape)

torch.Size([1, 2]) torch.Size([2, 1])


In [23]:
 #곱셈
print(torch.mm(m5,m6))

tensor([[11.]])


In [24]:
print(m5.matmul(m6))

tensor([[11.]])


In [26]:
print(torch.matmul(m5,m6))

tensor([[11.]])


In [28]:
# 요소곱
print(m5.mul(m6))

tensor([[3., 6.],
        [4., 8.]])


In [30]:
print(torch.mul(m5,m6))
print(m5 * m6)

tensor([[3., 6.],
        [4., 8.]])
tensor([[3., 6.],
        [4., 8.]])


In [31]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [32]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t.mean())

tensor(2.5000)


In [33]:
print(t.mean(dim=0))

tensor([2., 3.])


In [34]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [35]:
print(t.sum(dim=0))

tensor([4., 6.])


In [36]:
# 최대값
t = torch.FloatTensor([[1,2],[3,4]])
m = t.max() 

In [37]:
print(m)

tensor(4.)


In [38]:
print(t.max(dim=0)) # 열에 대한 최대값

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [39]:
print(t.max(dim=0)[0]) # 값만 출력

tensor([3., 4.])


In [40]:
print(t.max(dim=0)[1]) # 인덱스만 출력

tensor([1, 1])


In [42]:
t = torch.randn(2,2,3)
print(t)
print(t.shape)  # 12개 요소

tensor([[[ 0.2107, -1.1526, -0.6443],
         [-0.8916, -1.8968, -0.8235]],

        [[ 1.6979,  0.5829, -0.3853],
         [-0.0314,  0.9235, -0.5212]]])
torch.Size([2, 2, 3])


In [43]:
print(t.reshape([4,3]))  # 요소의 수가 같아야 함.

tensor([[ 0.2107, -1.1526, -0.6443],
        [-0.8916, -1.8968, -0.8235],
        [ 1.6979,  0.5829, -0.3853],
        [-0.0314,  0.9235, -0.5212]])


In [44]:
print(t.reshape([6,2]))

tensor([[ 0.2107, -1.1526],
        [-0.6443, -0.8916],
        [-1.8968, -0.8235],
        [ 1.6979,  0.5829],
        [-0.3853, -0.0314],
        [ 0.9235, -0.5212]])


In [45]:
print(t.view([3,4]))

tensor([[ 0.2107, -1.1526, -0.6443, -0.8916],
        [-1.8968, -0.8235,  1.6979,  0.5829],
        [-0.3853, -0.0314,  0.9235, -0.5212]])


In [46]:
print(t.shape)

torch.Size([2, 2, 3])


In [47]:
print(t.transpose(0,2))

tensor([[[ 0.2107,  1.6979],
         [-0.8916, -0.0314]],

        [[-1.1526,  0.5829],
         [-1.8968,  0.9235]],

        [[-0.6443, -0.3853],
         [-0.8235, -0.5212]]])


In [48]:
print(t.shape)

torch.Size([2, 2, 3])


In [53]:
t_n = t.permute(2,0,1) 
t_n.shape

torch.Size([3, 2, 2])

In [57]:
t_n=t.unsqueeze(1) #축 생성


In [58]:
print(t_n.shape)

torch.Size([2, 1, 2, 3])


In [59]:
print(t_n)

tensor([[[[ 0.2107, -1.1526, -0.6443],
          [-0.8916, -1.8968, -0.8235]]],


        [[[ 1.6979,  0.5829, -0.3853],
          [-0.0314,  0.9235, -0.5212]]]])


In [61]:
t_nn = t_n.squeeze()
print(t_nn.shape)

torch.Size([2, 2, 3])
